### ISSUE TITLE
If one player sends a message it looks for other players like they sent it

### ISSUE THREAD

**Issue by Tabbyploert** [ItzCandra23/rank-chat#1]
![image](https://user-images.githubusercontent.com/123080592/232253433-cfd393e1-8e25-4907-9564-86c61f40b8ef.png)

Only Tabbyploert sent a message. But it also prints the message for TabbyploertO. What could cause this? I am pretty new to this so I might have just done something stupid

**Comment by ItzCandra23** [comment]
Now in version 1.1.0 has been fixed, Thank you for informing.
